services:
  gestorpedidos-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=GestorPedidosDB;User=sa;Password=#40028922A#;Encrypt=false;TrustServerCertificate=true;
      - EnableSwagger=true

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      SA_PASSWORD: "#40028922A#"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "until timeout 1 bash -c '</dev/tcp/localhost/1433' 2>/dev/null; do sleep 1; done"]
      interval: 10s
      timeout: 5s
      retries: 10
    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

volumes:
  sql_data:
